version: '3.8'

services:
  comparator:
    build: .
    container_name: fsb_tpe_comparator
    ports:
      - "8080:8080"
    volumes:
      - ./history.db:/app/history.db
      - ./uploads:/app/uploads
      - ./backend/reports:/app/backend/reports
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: unless-stopped
