version: '3.8'

services:
  comparator:
    build: .
    container_name: fsb_tpe_comparator
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - ./history.db:/app/history.db
      - ./uploads:/app/uploads
      - ./frontend/static/reports:/app/frontend/static/reports
    env_file:
      - .env
    restart: unless-stopped
